{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0b6d810-d546-48f6-af5d-01ccdcc38e98",
   "metadata": {},
   "outputs": [],
   "source": [
    "#import cadquery\n",
    "#display(cadquery.Workplane('XY').box(1,2,3))\n",
    "\n",
    "# https://cadquery.readthedocs.io/en/latest/quickstart.html\n",
    "import cadquery as cq\n",
    "\n",
    "height = 60.0\n",
    "width = 80.0\n",
    "thickness = 10.0\n",
    "diameter = 22.0\n",
    "padding = 12.0\n",
    "\n",
    "result = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .box(height, width, thickness)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .hole(diameter)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .rect(height - padding, width - padding, forConstruction=True)\n",
    "    .vertices()\n",
    "    .cboreHole(2.4, 4.4, 2.1)\n",
    "    .edges(\"|Z\")\n",
    "    .fillet(2.0)\n",
    ")\n",
    "\n",
    "display(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c8265a8-54cb-4ac3-a213-d5fe73ac219e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# https://cadquery.readthedocs.io/en/latest/examples.html\n",
    "\n",
    "# parameter definitions\n",
    "p_outerWidth = 100.0  # Outer width of box enclosure\n",
    "p_outerLength = 150.0  # Outer length of box enclosure\n",
    "p_outerHeight = 50.0  # Outer height of box enclosure\n",
    "\n",
    "p_thickness = 3.0  # Thickness of the box walls\n",
    "p_sideRadius = 10.0  # Radius for the curves around the sides of the box\n",
    "p_topAndBottomRadius = (\n",
    "    2.0  # Radius for the curves on the top and bottom edges of the box\n",
    ")\n",
    "\n",
    "p_screwpostInset = 12.0  # How far in from the edges the screw posts should be place.\n",
    "p_screwpostID = 4.0  # Inner Diameter of the screw post holes, should be roughly screw diameter not including threads\n",
    "p_screwpostOD = 10.0  # Outer Diameter of the screw posts.\\nDetermines overall thickness of the posts\n",
    "\n",
    "p_boreDiameter = 8.0  # Diameter of the counterbore hole, if any\n",
    "p_boreDepth = 1.0  # Depth of the counterbore hole, if\n",
    "p_countersinkDiameter = 0.0  # Outer diameter of countersink. Should roughly match the outer diameter of the screw head\n",
    "p_countersinkAngle = 90.0  # Countersink angle (complete angle between opposite sides, not from center to one side)\n",
    "p_flipLid = True  # Whether to place the lid with the top facing down or not.\n",
    "p_lipHeight = 1.0  # Height of lip on the underside of the lid.\\nSits inside the box body for a snug fit.\n",
    "\n",
    "# outer shell\n",
    "oshell = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .rect(p_outerWidth, p_outerLength)\n",
    "    .extrude(p_outerHeight + p_lipHeight)\n",
    ")\n",
    "\n",
    "# weird geometry happens if we make the fillets in the wrong order\n",
    "if p_sideRadius > p_topAndBottomRadius:\n",
    "    oshell = oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "    oshell = oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "else:\n",
    "    oshell = oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "    oshell = oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "\n",
    "# inner shell\n",
    "ishell = (\n",
    "    oshell.faces(\"<Z\")\n",
    "    .workplane(p_thickness, True)\n",
    "    .rect((p_outerWidth - 2.0 * p_thickness), (p_outerLength - 2.0 * p_thickness))\n",
    "    .extrude(\n",
    "        (p_outerHeight - 2.0 * p_thickness), False\n",
    "    )  # set combine false to produce just the new boss\n",
    ")\n",
    "ishell = ishell.edges(\"|Z\").fillet(p_sideRadius - p_thickness)\n",
    "\n",
    "# make the box outer box\n",
    "box = oshell.cut(ishell)\n",
    "\n",
    "# make the screw posts\n",
    "POSTWIDTH = p_outerWidth - 2.0 * p_screwpostInset\n",
    "POSTLENGTH = p_outerLength - 2.0 * p_screwpostInset\n",
    "\n",
    "box = (\n",
    "    box.faces(\">Z\")\n",
    "    .workplane(-p_thickness)\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\n",
    "    .vertices()\n",
    "    .circle(p_screwpostOD / 2.0)\n",
    "    .circle(p_screwpostID / 2.0)\n",
    "    .extrude(-1.0 * (p_outerHeight + p_lipHeight - p_thickness), True)\n",
    ")\n",
    "\n",
    "# split lid into top and bottom parts\n",
    "(lid, bottom) = (\n",
    "    box.faces(\">Z\")\n",
    "    .workplane(-p_thickness - p_lipHeight)\n",
    "    .split(keepTop=True, keepBottom=True)\n",
    "    .all()\n",
    ")  # splits into two solids\n",
    "\n",
    "# translate the lid, and subtract the bottom from it to produce the lid inset\n",
    "lowerLid = lid.translate((0, 0, -p_lipHeight))\n",
    "cutlip = lowerLid.cut(bottom).translate(\n",
    "    (p_outerWidth + p_thickness, 0, p_thickness - p_outerHeight + p_lipHeight)\n",
    ")\n",
    "\n",
    "# compute centers for screw holes\n",
    "topOfLidCenters = (\n",
    "    cutlip.faces(\">Z\")\n",
    "    .workplane(centerOption=\"CenterOfMass\")\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\n",
    "    .vertices()\n",
    ")\n",
    "\n",
    "# add holes of the desired type\n",
    "if p_boreDiameter > 0 and p_boreDepth > 0:\n",
    "    topOfLid = topOfLidCenters.cboreHole(\n",
    "        p_screwpostID, p_boreDiameter, p_boreDepth, 2.0 * p_thickness\n",
    "    )\n",
    "elif p_countersinkDiameter > 0 and p_countersinkAngle > 0:\n",
    "    topOfLid = topOfLidCenters.cskHole(\n",
    "        p_screwpostID, p_countersinkDiameter, p_countersinkAngle, 2.0 * p_thickness\n",
    "    )\n",
    "else:\n",
    "    topOfLid = topOfLidCenters.hole(p_screwpostID, 2.0 * p_thickness)\n",
    "\n",
    "# flip lid upside down if desired\n",
    "if p_flipLid:\n",
    "    topOfLid = topOfLid.rotateAboutCenter((1, 0, 0), 180)\n",
    "\n",
    "# return the combined result\n",
    "result = topOfLid.union(bottom)\n",
    "\n",
    "display(result)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
